SEED_TASKS = [
    # Math Tasks
    {
        "title": "Linear Equation Solver",
        "description": "Solve for x: 3x + 5 = 2x - 10. Show your work.",
        "category": "math",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "x = -15",
    },
    {
        "title": "Prime Factorization",
        "description": "Factorize 123456789 into its prime components.",
        "category": "math",
        "difficulty": 4,
        "is_objective": True,
        "expected_answer": "3^2 × 3607 × 3803",
    },
    {
        "title": "Quadratic Equation",
        "description": "Solve for x: x^2 - 5x + 6 = 0.",
        "category": "math",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "x = 2 or x = 3",
    },
    {
        "title": "Calculus Limit",
        "description": "What is the limit of (sin x)/x as x approaches 0?",
        "category": "math",
        "difficulty": 3,
        "is_objective": True,
        "expected_answer": "1",
    },
    {
        "title": "Geometry Problem",
        "description": "A right triangle has legs of length 3 and 4. What is the length of the hypotenuse?",
        "category": "math",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "5",
    },
    {
        "title": "Sum of Series",
        "description": "What is the sum of the first 10 positive integers?",
        "category": "math",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "55",
    },
    {
        "title": "Exponential Equation",
        "description": "Solve for x: 2^x = 16.",
        "category": "math",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "x = 4",
    },
    {
        "title": "Probability Problem",
        "description": "What is the probability of rolling a sum of 7 with two fair six-sided dice?",
        "category": "math",
        "difficulty": 3,
        "is_objective": True,
        "expected_answer": "1/6",
    },
    {
        "title": "Matrix Multiplication",
        "description": "Multiply the matrices [[1, 2], [3, 4]] and [[5, 6], [7, 8]].",
        "category": "math",
        "difficulty": 3,
        "is_objective": True,
        "expected_answer": "[[19, 22], [43, 50]]",
    },
    {
        "title": "Trigonometry",
        "description": "What is the value of sin(π/2) in radians?",
        "category": "math",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "1",
    },
    
    # Logic Tasks
    {
        "title": "Syllogism",
        "description": "If all Bloops are Razzies and all Razzies are Lazzies, are all Bloops Lazzies?",
        "category": "logic",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "Yes",
    },
    {
        "title": "Truth Table",
        "description": "Generate the truth table for: (A AND B) OR (NOT C).",
        "category": "logic",
        "difficulty": 3,
        "is_objective": True,
        "expected_answer": "A | B | C | Result\n0 | 0 | 0 | 1\n0 | 0 | 1 | 0\n0 | 1 | 0 | 1\n0 | 1 | 1 | 1\n1 | 0 | 0 | 1\n1 | 0 | 1 | 1\n1 | 1 | 0 | 1\n1 | 1 | 1 | 1",
    },
    {
        "title": "Logical Deduction",
        "description": "If it rains, the ground is wet. The ground is wet. Did it rain?",
        "category": "logic",
        "difficulty": 3,
        "is_objective": False,
        "expected_answer": None,
    },
    {
        "title": "Modus Ponens",
        "description": "If P, then Q. P is true. Is Q true?",
        "category": "logic",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "Yes",
    },
    {
        "title": "Modus Tollens",
        "description": "If P, then Q. Q is false. Is P false?",
        "category": "logic",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "Yes",
    },
    {
        "title": "Contrapositive",
        "description": "What is the contrapositive of 'If it is a dog, then it is a mammal'?",
        "category": "logic",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "If it is not a mammal, then it is not a dog",
    },
    {
        "title": "Set Theory",
        "description": "If A = {1, 2, 3} and B = {3, 4, 5}, what is A ∪ B?",
        "category": "logic",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "{1, 2, 3, 4, 5}",
    },
    {
        "title": "Venn Diagram",
        "description": "If all X are Y and no Y are Z, can any X be Z?",
        "category": "logic",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "No",
    },
    {
        "title": "Paradox",
        "description": "Explain the 'This statement is false' paradox in 2 sentences.",
        "category": "logic",
        "difficulty": 4,
        "is_objective": False,
        "expected_answer": None,
    },
    {
        "title": "Boolean Algebra",
        "description": "Simplify: A AND (A OR B).",
        "category": "logic",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "A",
    },
    
    # Code Tasks
    {
        "title": "Reverse a Linked List",
        "description": "Write a Python function to reverse a linked list in-place.",
        "category": "code",
        "difficulty": 4,
        "is_objective": True,
        "expected_answer": "def reverse_list(head):\n    prev = None\n    current = head\n    while current:\n        next_node = current.next\n        current.next = prev\n        prev = current\n        current = next_node\n    return prev",
    },
    {
        "title": "FizzBuzz",
        "description": "Write a Python function that prints FizzBuzz for numbers 1-100.",
        "category": "code",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "def fizzbuzz():\n    for i in range(1, 101):\n        if i % 15 == 0:\n            print('FizzBuzz')\n        elif i % 3 == 0:\n            print('Fizz')\n        elif i % 5 == 0:\n            print('Buzz')\n        else:\n            print(i)",
    },
    {
        "title": "Binary Search",
        "description": "Write a Python function to perform binary search on a sorted list.",
        "category": "code",
        "difficulty": 3,
        "is_objective": True,
        "expected_answer": "def binary_search(arr, target):\n    low, high = 0, len(arr) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1",
    },
    {
        "title": "Fibonacci Sequence",
        "description": "Write a Python function to generate the first n Fibonacci numbers.",
        "category": "code",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "def fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b",
    },
    {
        "title": "Palindrome Checker",
        "description": "Write a Python function to check if a string is a palindrome.",
        "category": "code",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "def is_palindrome(s):\n    return s == s[::-1]",
    },
    {
        "title": "Merge Sort",
        "description": "Write a Python function to implement merge sort.",
        "category": "code",
        "difficulty": 4,
        "is_objective": True,
        "expected_answer": "def merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] < right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result",
    },
    {
        "title": "Debugging",
        "description": "This Python function is supposed to return the sum of a list but has a bug. Fix it: def sum_list(lst):\n    total = 0\n    for num in lst:\n        total += num\n    return total",
        "category": "code",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "The function is correct",
    },
    {
        "title": "List Comprehension",
        "description": "Write a Python list comprehension to generate the squares of the first 10 natural numbers.",
        "category": "code",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "[i**2 for i in range(1, 11)]",
    },
    {
        "title": "Recursion",
        "description": "Write a Python function to compute the factorial of a number using recursion.",
        "category": "code",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "def factorial(n):\n    if n == 0:\n        return 1\n    return n * factorial(n - 1)",
    },
    {
        "title": "Class Implementation",
        "description": "Write a Python class to represent a stack with push, pop, and peek methods.",
        "category": "code",
        "difficulty": 3,
        "is_objective": True,
        "expected_answer": "class Stack:\n    def __init__(self):\n        self.items = []\n    def push(self, item):\n        self.items.append(item)\n    def pop(self):\n        return self.items.pop()\n    def peek(self):\n        return self.items[-1] if self.items else None",
    },
    
    # Language Tasks
    {
        "title": "Analogies",
        "description": "King is to queen as rooster is to ___.",
        "category": "language",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "hen",
    },
    {
        "title": "Text Summarization",
        "description": "Summarize the following paragraph in 1 sentence: 'The Industrial Revolution was a period of major industrialization that began in the late 1700s and transformed largely agrarian societies into industrialized ones. It started in Great Britain and spread to other parts of the world. This period saw the introduction of machinery, the factory system, and mass production.'",
        "category": "language",
        "difficulty": 3,
        "is_objective": False,
        "expected_answer": None,
    },
    {
        "title": "Translation",
        "description": "Translate 'Hello, how are you?' to French.",
        "category": "language",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "Bonjour, comment ça va ?",
    },
    {
        "title": "Synonyms",
        "description": "What is a synonym for 'happy'?",
        "category": "language",
        "difficulty": 1,
        "is_objective": False,
        "expected_answer": None,
    },
    {
        "title": "Antonyms",
        "description": "What is an antonym for 'hot'?",
        "category": "language",
        "difficulty": 1,
        "is_objective": False,
        "expected_answer": None,
    },
    {
        "title": "Grammar Correction",
        "description": "Correct the following sentence: 'She dont have no idea.'",
        "category": "language",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "She doesn't have any idea.",
    },
    {
        "title": "Word Definition",
        "description": "Define the word 'ephemeral'.",
        "category": "language",
        "difficulty": 2,
        "is_objective": False,
        "expected_answer": None,
    },
    {
        "title": "Sentence Completion",
        "description": "Complete the sentence: 'The early bird ___ the worm.'",
        "category": "language",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "catches",
    },
    {
        "title": "Idiom Explanation",
        "description": "Explain the meaning of the idiom 'hit the hay'.",
        "category": "language",
        "difficulty": 2,
        "is_objective": False,
        "expected_answer": None,
    },
    {
        "title": "Rhyme Time",
        "description": "Write a word that rhymes with 'cat'.",
        "category": "language",
        "difficulty": 1,
        "is_objective": False,
        "expected_answer": None,
    },
    
    # Science Tasks
    {
        "title": "Chemistry",
        "description": "Balance the equation: H2 + O2 -> H2O.",
        "category": "science",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "2H2 + O2 -> 2H2O",
    },
    {
        "title": "Physics",
        "description": "A car accelerates at 2 m/s² from rest. How far does it travel in 5 seconds?",
        "category": "science",
        "difficulty": 3,
        "is_objective": True,
        "expected_answer": "25 meters",
    },
    {
        "title": "Biology",
        "description": "What is the powerhouse of the cell?",
        "category": "science",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "mitochondria",
    },
    {
        "title": "Astronomy",
        "description": "What is the largest planet in our solar system?",
        "category": "science",
        "difficulty": 1,
        "is_objective": True,
        "expected_answer": "Jupiter",
    },
    {
        "title": "Earth Science",
        "description": "What causes tides on Earth?",
        "category": "science",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "The gravitational pull of the Moon",
    },
    {
        "title": "Genetics",
        "description": "If a parent has genotype Aa and the other has aa, what is the probability their child will have genotype aa?",
        "category": "science",
        "difficulty": 3,
        "is_objective": True,
        "expected_answer": "50%",
    },
    {
        "title": "Chemical Bonding",
        "description": "What type of bond forms between sodium (Na) and chlorine (Cl)?",
        "category": "science",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "Ionic bond",
    },
    {
        "title": "Newton's Laws",
        "description": "What is Newton's Third Law of Motion?",
        "category": "science",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "For every action, there is an equal and opposite reaction",
    },
    {
        "title": "Evolution",
        "description": "What is the process by which organisms better adapted to their environment tend to survive and produce more offspring?",
        "category": "science",
        "difficulty": 2,
        "is_objective": True,
        "expected_answer": "Natural selection",
    },
    {
        "title": "Quantum Physics",
        "description": "Explain the concept of quantum superposition in 2 sentences.",
        "category": "science",
        "difficulty": 5,
        "is_objective": False,
        "expected_answer": None,
    },
]
